[package]
name = "xml_song_extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13"
rfd = "0.15"            # Native File & Folder Dialogs
quick-xml = "0.37"      # Fast XML Parser
encoding_rs = "0.8"     # Robust UTF-8 / UTF-16 decoding
dark-light = "1.0"      # Queries the system settings to determine Dark or Light mode

[build-dependencies]
winres = "0.1"